# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
markdown: redcarpet
paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
pygments: true

title: Prathamesh Sonpatki - Blog
description: "Prathamesh Sonpatki's blog"
author:
  name: Prathamesh Sonpatki
  email: csonpatki@gmail.com
  github: prathamesh-sonpatki
  twitter: _cha1tanya
  bio: Programmer
  email_md5: 1b0973b64704738dbc8ce24d8382bb1f
rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH: http://cha1tanya.com